name: Build and Test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make build directory
      run: mkdir build

    - name: Configure cmake
      run: cmake ..
      working-directory: ${{ github.workspace }}/build

    - name: Build
      run: cmake --build .
      working-directory: ${{ github.workspace }}/build

    - name: Run Test
      run: ./convergence-test.ex
      working-directory: ${{ github.workspace }}/build
